version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: ''
    AWS_DEFAULT_REGION: ''
    PUBLISH: ''

phases:
  build:
    commands:
      - mkdir -p ~/.docker
      - echo '{"credsStore":"ecr-login"}' > ~/.docker/config.json
      - ./build.sh -a ${PUBLISH:+-p}
