#!/bin/bash

# TEST_VERSIONS: 2.7.12 3.5.2

### Description
# This script uses fpm to build and package Python.
# In order to not interfere with the system version of Python, I
# opted to call this package 'python-local'.

# Required Environment Variables:
#   - BUILD_VERSION
#   - BUILD_ITERATION
#   - BUILD_OUTPUT_DIR

# Example Usage:
#   The following command will create /tmp/python-local-3.5.2-1.rpm
#     $ BUILD_VERSION=3.5.2 BUILD_ITERATION=1 BUILD_OUTPUT_DIR=/tmp build_python

# Install dependencies
yum update -y
yum groupinstall -y development
yum install -y \
  bzip2-devel \
  expat-devel \
  gdbm-devel \
  libdb-devel \
  libffi-devel \
  ncurses-devel \
  openssl-devel \
  python-devel \
  readline-devel \
  sqlite-devel \
  tk-devel \
  xz-devel \
  zlib-devel

# Build Python
cd /tmp
curl -so Python-${BUILD_VERSION}.tgz https://www.python.org/ftp/python/${BUILD_VERSION}/Python-${BUILD_VERSION}.tgz
tar xfv Python-${BUILD_VERSION}.tgz
cd Python-${BUILD_VERSION}
./configure --prefix=/usr/local; make
mkdir /tmp/python_build
make install DESTDIR=/tmp/python_build

# Create .rpm package
fpm -s dir -t rpm \
  -C /tmp/python_build/ \
  --name python-local \
  --version ${BUILD_VERSION} \
  --iteration ${BUILD_ITERATION} \
  --package ${BUILD_OUTPUT_DIR}/python-local-VERSION-ITERATION.rpm \
  --description "Install Python ${BUILD_VERSION} to /usr/local/" \
  --depends bzip2 \
  --depends expat \
  --depends gdbm \
  --depends glibc \
  --depends libdb \
  --depends libffi \
  --depends ncurses \
  --depends openssl \
  --depends readline \
  --depends sqlite \
  --depends zlib
