#!/bin/bash

# TEST_VERSIONS: 2.7.12 3.5.2

### Description
# This script uses fpm to build and package Python.
# In order to not interfere with the system version of Python, I
# opted to call this package 'python-local'. Dependencies for
# python-local are based on the packages used to build python-local
# and the existing Debian Python dependency tree.

# Required Environment Variables:
#   - BUILD_VERSION
#   - BUILD_ITERATION
#   - BUILD_OUTPUT_DIR

# Example Usage:
#   The following command will create /tmp/python-local-3.5.2-1.deb
#     $ BUILD_VERSION=3.5.2 BUILD_ITERATION=1 BUILD_OUTPUT_DIR=/tmp build_python

# Exit immediately when command fails
set -ex

# Install dependencies
apt-get update
apt-get install -y \
  build-essential \
  libbz2-dev \
  libdb-dev \
  libexpat1-dev \
  libffi-dev \
  libgdbm-dev \
  liblzma-dev \
  libncursesw5-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  python-dev \
  tk-dev \
  wget \
  zlib1g-dev

# Build Python
cd /tmp
wget https://www.python.org/ftp/python/${BUILD_VERSION}/Python-${BUILD_VERSION}.tgz
tar xfv Python-${BUILD_VERSION}.tgz
cd Python-${BUILD_VERSION}
./configure --prefix=/usr/local; make
mkdir /tmp/python_build
make install DESTDIR=/tmp/python_build

# Install pip
cd /tmp
wget https://bootstrap.pypa.io/get-pip.py
/tmp/python_build/usr/local/bin/python${BUILD_VERSION::1} /tmp/get-pip.py

# Install virtualenv for python2
[ "${BUILD_VERSION::1}" -eq 2 ] && /tmp/python_build/usr/local/bin/pip install virtualenv

# Create .deb package
fpm -s dir -t deb \
  -C /tmp/python_build/ \
  --name python-local \
  --version ${BUILD_VERSION} \
  --iteration ${BUILD_ITERATION} \
  --package ${BUILD_OUTPUT_DIR}/python-local-VERSION-ITERATION.deb \
  --description "Install Python ${BUILD_VERSION} to /usr/local/" \
  --depends libbz2-1.0 \
  --depends libc6 \
  --depends libdb5.3 \
  --depends libexpat1 \
  --depends libffi6 \
  --depends libncursesw5 \
  --depends libreadline6 \
  --depends libsqlite3-0 \
  --depends libssl1.0.0 \
  --depends libtinfo5 \
  --depends mime-support \
  --depends zlib1g
